language: python
python:
  - 3.8

install:
  - pip install -r requirements.txt


script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  region: "us-east-1"
  app: "swe1-app"
  env: "swe1-app-dev"