os: linux
dist: focal
language: python

python:
  - 3.8

addons:
  postgresql: '13'
  apt:
      packages:
        - postgresql-13

env:
  global:
   - PGUSER=postgres
   - PGPORT=5432
   - PGHOST=localhost

before_install:
 - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
 - sudo service postgresql restart
 - sleep 1
 - postgres --version

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database djangopolls;' -U postgres
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  region: "us-east-1"
  app: "swe1-app"
  env: "swe1-app-dev"
  bucket_name: "djangopollslp"
  on:
    repo: louispo0603/swe1-app
    branch: main

after_script:
  - coveralls
