os: linux
dist: jammy
language: python

python:
  - 3.8

env:
  - HOST_URL="localhost"
  global:
    - PGPORT=5433
cache:
  directories:
    - $HOME/path/to/local
services:
  - postgresql
addons:
  postgresql: 13
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13
    - libpq-dev
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - clang-tidy

before_install:
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/a/astyle/astyle_3.1-1ubuntu2_amd64.deb
  - sudo dpkg -i astyle_3.1-1ubuntu2_amd64.deb
  - sudo chmod -R 777 /var/log/

install:
  - pip install -r requirements.txt

before_script:
  - psql -p 5433 -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  region: "us-east-1"
  app: "swe1-app"
  env: "swe1-app-dev"
  on:
    repo: louispo0603/swe1-app
    branch: main

after_success:
  - curl -L https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.exe -o coveralls.exe
