os: linux
dist: jammy
language: python

python:
  - 3.8

services:
  - postgresql

addons:
  # Use a different PostgreSQL version than the default:
  postgresql: 13
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-13-postgis-3

env:
  global:
    - PGPORT=5433
  jobs:
    - NODE_ENV=test DB_PORT=5433 DB_USERNAME=postgres

before_install:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  - sudo service postgresql@13-main restart

install:
  - pip install -r requirements.txt

before_script:
  - sudo psql -r 5433 -U postgre -c 'create database my-app;'
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  region: "us-east-1"
  app: "swe1-app"
  env: "swe1-app-dev"
  on:
    repo: louispo0603/swe1-app
    branch: main

after_success:
  - curl -L https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.exe -o coveralls.exe
